// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: test/base/webserver.proto
#ifndef GRPC_test_2fbase_2fwebserver_2eproto__INCLUDED
#define GRPC_test_2fbase_2fwebserver_2eproto__INCLUDED

#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/server_context.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

#include <functional>

#include "test/base/example/webserver.pb.h"

namespace go {
namespace pkg {
namespace webserver {}  // namespace webserver
}  // namespace pkg
}  // namespace go

#endif  // GRPC_test_2fbase_2fwebserver_2eproto__INCLUDED
